version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    target-branch: "shared"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Git submodule"
    labels:
      - "dependencies"
