name: Flutter Nightly Build

on:
  push:
    tags:
      - 'test*' #仅限带有（test-xxx标签的tag时候触发）
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.ref_name }}
